# Generated by Django 2.1.1 on 2020-03-24 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_amount', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Financial_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.FloatField()),
                ('monthly_expenses', models.FloatField()),
                ('bank_statement', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Diseases')),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('base_amt', models.FloatField()),
                ('package_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Packages')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=50)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Packages')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_num', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('ID_proof', models.CharField(max_length=25)),
                ('Address_proof', models.CharField(max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='purchase_details',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Users'),
        ),
        migrations.AddField(
            model_name='medical_history',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Users'),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='package_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Packages'),
        ),
        migrations.AddField(
            model_name='financial_history',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Users'),
        ),
        migrations.AddField(
            model_name='diseases',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Services'),
        ),
        migrations.AddField(
            model_name='claim_history',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Services'),
        ),
        migrations.AddField(
            model_name='claim_history',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Users'),
        ),
        migrations.AlterUniqueTogether(
            name='medical_history',
            unique_together={('user_id', 'disease_id')},
        ),
    ]
