# Generated by Django 2.1.1 on 2020-04-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200413_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='disease_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='financial_history',
            name='bank_statement',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='hospital_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='Address_proof',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='users',
            name='ID_proof',
            field=models.CharField(max_length=55),
        ),
    ]
